services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - .env
    networks:
      - app_network
    ports:
      - 127.0.0.1:5432:5432
  solidjs:
    build:
      context: .
      dockerfile: apps/solidjs/Dockerfile
    env_file:
      - .env
    networks:
      - app_network
    ports:
      - 127.0.0.1:3000:3000
  nestjs:
    build:
      context: .
      dockerfile: apps/nestjs/Dockerfile
    env_file:
      - .env
    networks:
      - app_network
    ports:
      - 127.0.0.1:3001:3001

networks:
  app_network:
    driver: bridge
