services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - db_network
    ports:
      - 5432:5432
  solidjs:
    build:
      context: .
      dockerfile: apps/solidjs/Dockerfile
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - 3000:3000
